general: {}
plots:
  fit:
    model_images_of_planes: false
    plane_images_of_planes: false
    subplots_of_planes_fits: true
    subtracted_images_of_planes: false
  other:
    stochastic_histogram: false
  positions:
    image_with_positions: true
  ray_tracing:
    all_at_end_fits: false
    all_at_end_png: false
    convergence: false
    deflections: false
    image: false
    magnification: false
    potential: false
    source_plane_image: false
    subplot_plane_images: true
    subplot_ray_tracing: true
