general:
  general:
    backend: default
    imshow_origin: upper
    zoom_around_mask: true
include:
  include_2d:
    border: true
    tangential_caustics: false
    radial_caustics: false
    tangential_critical_curves: false
    radial_critical_curves: false
    grid: true
    inversion_grid: true
    light_profile_centres: true
    mapper_image_plane_mesh_grid: false
    mapper_source_plane_mesh_grid: true
    mask: true
    mass_profile_centres: true
    multiple_images: false
    origin: true
    parallel_overscan: true
    positions: true
    serial_overscan: true
    serial_prescan: true
mat_wrap_2d:
  CausticsLine:
    figure:
      c: w,g
      linestyle: --
      linewidth: 5
    subplot:
      c: g
      linestyle: --
      linewidth: 7
  CriticalCurvesLine:
    figure:
      c: w,k
      linestyle: '-'
      linewidth: 4
    subplot:
      c: b
      linestyle: '-'
      linewidth: 6
  LightProfileCentreScatter:
    figure:
      c: k,r
      marker: +
      s: 1
    subplot:
      c: b
      marker: .
      s: 15
  MassProfileCentreScatter:
    figure:
      c: r,k
      marker: x
      s: 2
    subplot:
      c: k
      marker: o
      s: 16
  MultipleImagesScatter:
    figure:
      c: k,w
      marker: o
      s: 3
    subplot:
      c: g
      marker: .
      s: 17
plots:
  dataset:
    subplot_dataset: true
  fit:
    subplot_fit: true
    subplots_of_planes: false
  fit_imaging: {}
  fit_interferometer:
    subplot_fit_real_space: true
    subplot_fit_dirty_images: true
  fit_point_dataset: {}
  fit_quantity:
    subplot_fit: true
  galaxies:
    subplot_galaxies: true
    subplot_galaxy_images: true
    subplot_galaxies_1d: true
    subplot_galaxies_1d_decomposed: true
  adapt:
    subplot_adapt_images: true
  inversion:
    subplot_inversion: true
  positions:
    image_with_positions: true
  tracer:
    subplot_tracer: true
    subplot_galaxies_images: true